const CyrillicToLatinMappingLowercase = {
    "а": "а",
    "б": "b",
    "в": "v",
    "г": "g",
    "д": "d",
    "е": "e",
    "ж": "zh",
    "з": "z",
    "и": "i",
    "й": "y",
    "к": "k",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "п": "p",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "u",
    "ф": "f",
    "х": "h",
    "ц": "ts",
    "ч": "ch",
    "ш": "sh",
    "щ": "sht",
    "ъ": "y",
    "ю": "yu",
    "я": "ya",
    "ь": "y"
}
Object.freeze(CyrillicToLatinMappingLowercase)
window.LetterMapping.letters.set(window.LetterMapping.keys.CyrillicToLatinMappingLowercase, CyrillicToLatinMappingLowercase)